@legacyBaseUrl = http://localhost:6003/

### Bare
POST {{legacyBaseUrl}}CityFinderServiceSoap.asmx
Content-Type: text/xml
SOAPAction: http://example.com/CityFinderService/FindCitiesActionBare

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://example.com/CityFinderService">
	<soapenv:Header></soapenv:Header>
	<soapenv:Body>
		<ns:findCities>
			 <country>US</country>
	         <zipCode></zipCode>
	         <city></city>
	         <limit>10</limit>
	         <order></order>
		</ns:findCities>
	</soapenv:Body>
</soapenv:Envelope>


### Default
POST {{legacyBaseUrl}}CityFinderServiceSoap.asmx
Content-Type: text/xml
SOAPAction: http://example.com/CityFinderService/FindCitiesActionDefault

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://example.com/CityFinderService">
	<soapenv:Header></soapenv:Header>
	<soapenv:Body>
		<ns:findCities>
			 <country>US</country>
	         <zipCode></zipCode>
	         <city></city>
	         <limit>10</limit>
	         <order></order>
		</ns:findCities>
	</soapenv:Body>
</soapenv:Envelope>
